#!/bin/bash
MYDIR="$(dirname "$(readlink -f "$0")")"
. "$MYDIR/config"

cd "$TOP"

# set up
export CYANOGEN_NIGHTLY=1
. "$ANDROID_BUILD_TOP/build/envsetup.sh" || exit 1
breakfast $DEVICE || exit 1

if [ "$1" = "clean" ]; then
    if [ -n "$KERNEL_DIR" ]; then
        "$KERNEL_DIR/build.sh" clean
        rm -rf "$KERNEL_DIR/build/.ccache"
    fi
    make clean
    rm -rf "$ANDROID_BUILD_TOP/out"
else
    # build kernel
    if [ -n "$KERNEL_DIR" ]; then
        "$KERNEL_DIR/build.sh" $DEVICE || exit 1
    fi
    
    # build android
    find "$ANDROID_BUILD_TOP/out/target/product/$DEVICE" -name build.prop | xargs rm
    mka bacon || exit 1
    
    # package
    pkgname=cm-$(awk -F= '$1 == "ro.build.version.incremental" { print $2 }' "$ANDROID_BUILD_TOP/out/target/product/$DEVICE/system/build.prop")
    zipfile="$MYDIR/${pkgname}.zip"
    "$MYDIR/repack-updatezip" "$ANDROID_BUILD_TOP/out/target/product/$DEVICE/update-squished.zip" "$GAPPS_PATH" $zipfile || exit 1
    echo "Successfully built $pkgname"
    [ "$1" = "update" ] && "$MYDIR/update" "$zipfile"
fi

exit 0
