#!/bin/sh
MYDIR="$(dirname "$(readlink -f "$0")")"
. "$MYDIR/config"

nightly="$1"
gapps="$2"
out="$3"

set -ex

nightlytmp="$(mktemp -d cmrepack-nightly.XXXXXXXXX)"
unzip -d "$nightlytmp" "$nightly"

for apk in RomManager FileManager; do
    rm -vf "$nightlytmp/system/app/${apk}.apk"
done

gappstmp="$(mktemp -d cmrecpack-gapps.XXXXXXXXX)"
unzip -d "$gappstmp" "$gapps"

(cd "$gappstmp"; find system -type f) | while read fn; do
    mkdir -p "$nightlytmp/$(dirname "$fn")"
    cp -v "$gappstmp/$fn" "$nightlytmp/$fn"
done

# files in gapps package
gappsfiles="$(find "$gappstmp/system" -type f|while read f; do basename $f; done|tr '\n' '|'|sed -e 's/\./\\./g;s/|$//')"
rm -rf "$gappstmp"

# don't backup & restore the files that are contained in the gapps package over an update
bpttemp="$(tempfile)"
grep -Ev "$gappsfiles" "$nightlytmp/system/bin/backuptool.sh" > "$bpttemp"
mv "$bpttemp" "$nightlytmp/system/bin/backuptool.sh"

tmpzip="$(tempfile)"
(cd "$nightlytmp"; zip -r - .) > "$tmpzip"
rm -rf "$nightlytmp"

SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
java -Xmx512m \
    -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
    -w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
    "$tmpzip" "$out"

rm -vf "$tmpzip"
