#!/bin/sh
set -e

zip="$1"
p=/sdcard/1updates/ # MUST end in /

adb push "$zip" "$p"
adb shell "echo -n > /cache/recovery/extendedcommand"
[ "$1" != "nobackup" ] && adb shell "$(z99local/backup getcmd)"
adb shell "echo 'install_zip(\"$p$(basename "$zip")\");' >> /cache/recovery/extendedcommand"
adb reboot recovery
